name: Build & Deploy
on:
  push:
    tags:
      - '@sammarks/**@**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies & Build
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        env:
          CI: true
          NODE_ENV: test
  deploy-github:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com/'
      - name: Install Dependencies
        run: yarn
      - name: Publish to Github
        run: 'yarn publish:github'
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM
        run: 'yarn publish:npm'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

