name: Build
on:
  push:
    tags-ignore:
      - '@sammarks/**@**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies & Build
        run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        env:
          CI: true
          NODE_ENV: test
